version: '3.7'

# L'ordre de lancement des services est défini par les depends_on
services:
  db:
    build: ./mariadb/
    environment:
      MYSQL_DATABASE:       db
      MYSQL_USER:           wp_user
      MYSQL_PASSWORD:       test
      MYSQL_ROOT_PASSWORD:  test
    networks:
      - wp_net
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build: ./wordpress/
    environment:
      DB_HOST:      db
      DB_USER:      wp_user
      DB_PASS:      test
      DB_NAME:      db
      DB_PREFIX:    wp_
      WP_URL:       http://jchapell.42.fr
      WP_TITLE:     "42"
      WP_ADMIN:     admin
      WP_PASS:      admin
      WP_MAIL:      jocraft2s@gmail.com
    networks:
      - wp_net
    depends_on:
      - db
    volumes:
      - wp_data:/var/www/html

  nginx:
    build: ./nginx/
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - wp_net
    volumes:
      - wp_data:/var/www/html

networks:
  wp_net:
    driver: bridge

volumes:
  db_data:
  wp_data: