version: '3.7'

services:
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - wp_net
    
  wordpress:
    build: ./wordpress/
    environment:
      WORDPRESS_DB_HOST:      db
      WORDPRESS_DB_USER:      root
      WORDPRESS_DB_PASSWORD:  test
      WORDPRESS_DB_NAME:      wordpress
    networks:
      - wp_net
  
  db:
    build: ./mariadb/
    environment:
      MYSQL_ROOT_PASSWORD:  test
      MYSQL_DATABASE:       wordpress
    networks:
      - wp_net

networks:
  wp_net: