version: '3.7'

# L'ordre de lancement des services est défini par les depends_on
services:
  db:
    build: ./mariadb/
    env_file:
      - .env
    networks:
      - wp_net
    volumes:
      - db_data:/var/lib/mysql
    container_name: db

  wordpress:
    build: ./wordpress/
    env_file:
      - .env
    networks:
      - wp_net
    depends_on:
      - db
    volumes:
      - wp_data:/var/www/html

  nginx:
    build: ./nginx/
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - wp_net
    volumes:
      - wp_data:/var/www/html

networks:
  wp_net:
    driver: bridge

volumes:
  db_data:
  wp_data: