version: '3.7'

services:
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - wp_net
    volumes:
      - wp:/var/www/html
  wordpress:
    build: ./wordpress/
    ports:
      - "9000:9000"
    environment:
      DB_HOST:      db
      DB_USER:      root
      DB_PASS:  test
      DB_NAME:      wordpress
      DB_PREFIX:    wp_
      WP_URL:       localhost
      WP_TITLE:     "42"
      WP_ADMIN:     admin
      WP_PASS:      admin
      WP_MAIL:      jocraft2s@gmail.com
    networks:
      - wp_net
    volumes:
      - wp:/var/www/html
  
  db:
    build: ./mariadb/
    environment:
      MYSQL_ROOT_PASSWORD:  test
      MYSQL_DATABASE:       wordpress
    networks:
      - wp_net

networks:
  wp_net:
volumes:
 wp:
    driver: local
    driver_opts:
      type: none
      o: bind
