version: '3.7'

services:
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - wp_net
    volumes:
      - db_data:/var/lib/mysql

  db:
    build: ./mariadb/
    environment:
      MYSQL_DATABASE:       wordpress
      MYSQL_USER:           wp_user
      MYSQL_PASSWORD:       test
    networks:
      - wp_net

  wordpress:
    build: ./wordpress/
    environment:
      DB_HOST:      db
      DB_USER:      wp_user
      DB_PASS:      test
      DB_NAME:      wp_db
      DB_PREFIX:    wp_
      WP_URL:       http://localhost
      WP_TITLE:     "42"
      WP_ADMIN:     admin
      WP_PASS:      admin
      WP_MAIL:      jocraft2s@gmail.com
    networks:
      - wp_net
    depends_on:
      - db

networks:
  wp_net:

volumes:
  db_data: